"""
Typst Academic Document Generator for SynapseForge.
Compiles modular Markdown into publication-grade Typst sources for high-resolution vector PDFs.
"""

from __future__ import annotations

import re
from typing import List, Optional

from synapseforge.core.ast_parser import BlockType, MarkdownASTParser
from synapseforge.tools.pdf_tool import PDFTool

# Shared LaTeX-math / Markdown-table converters from the PDF pipeline.
_PDF_TOOL = PDFTool()


def _escape_typst_str(s: str) -> str:
    """Escapes a string for embedding inside a Typst string literal (code mode)."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _escape_typst_content(s: str) -> str:
    """Escapes text for embedding inside a Typst markup content block."""
    return (
        s.replace("\\", "\\\\")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("#", "\\#")
    )


class TypstRenderer:
    """Transforms parsed Markdown documents into publication-ready Typst code."""

    @staticmethod
    def render(markdown_text: str, title: str, authors: Optional[List[str]] = None) -> str:
        authors_list = authors or ["SynapseForge Collaborative Swarm"]
        authors_typst = ", ".join([f'"{_escape_typst_str(a)}"' for a in authors_list])
        title_str = _escape_typst_str(title)
        title_content = _escape_typst_content(title)
        authors_content = _escape_typst_content(", ".join(authors_list))

        out: List[str] = [
            '// Typst Academic Publication Source generated by SynapseForge',
            '#set document(title: "' + title_str + '", author: (' + authors_typst + '))',
            '#set page(paper: "a4", margin: (x: 2.2cm, top: 2.5cm, bottom: 2.5cm))',
            '#set text(font: ("KaiTi", "STKaiti", "Times New Roman"), size: 10.5pt, lang: "zh")',
            '#set par(justify: true, first-line-indent: 2em, leading: 0.75em)',
            '#set heading(numbering: "1.1")',
            '',
            '#align(center)[',
            '  #text(size: 20pt, weight: "bold", font: ("SimHei", "STHeiti", "Times New Roman"))[' + title_content + ']',
            '  #v(1em)',
            '  #text(size: 11pt, style: "italic")[' + authors_content + ']',
            '  #v(1.5em)',
            ']',
            '',
            '#outline(depth: 3, indent: auto)',
            '#v(2em)',
            '',
        ]

        blocks = MarkdownASTParser.parse_blocks(markdown_text)
        for b in blocks:
            if b.type == BlockType.HEADING:
                level = b.level or 1
                prefix = "=" * level
                out.append(f"{prefix} {_escape_typst_content(b.title)}\n")
            elif b.type == BlockType.PARAGRAPH:
                clean_p = b.content.strip()
                # Check for images: ![caption](path)
                img_m = re.match(r'^!\[(.*?)\]\((.*?)\)$', clean_p)
                if img_m:
                    caption, img_path = img_m.group(1), img_m.group(2)
                    out.append(f'#figure(image("{_escape_typst_str(img_path)}", width: 85%), caption: [{_escape_typst_content(caption)}])\n')
                else:
                    # Convert inline LaTeX math ($...$) into Typst math syntax.
                    out.append(_PDF_TOOL._convert_latex_math_to_typst(clean_p) + "\n")
            elif b.type == BlockType.BLOCKQUOTE:
                out.append(f'#block(fill: rgb("f0f4f8"), inset: 12pt, radius: 4pt)[\n{b.content}\n]\n')
            elif b.type == BlockType.CODE_BLOCK:
                lang = b.metadata.get("lang", "")
                out.append(f"```{lang}\n{b.content}\n```\n")
            elif b.type == BlockType.MATH_BLOCK:
                # Convert LaTeX display math ($$...$$) into Typst math syntax.
                out.append(_PDF_TOOL._convert_latex_math_to_typst(f"$${b.content}$$").strip() + "\n")
            elif b.type == BlockType.TABLE:
                # Convert the raw Markdown pipe table into a real Typst #table(...).
                out.append(_PDF_TOOL._convert_markdown_tables_to_typst(b.content).strip() + "\n")

        return "\n".join(out)
